# Generated by Django 4.1.2 on 2023-11-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('pic', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=300)),
                ('pswd', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
